# Generated by Django 5.2 on 2025-04-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExperiencePro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entreprise", models.CharField(max_length=60)),
                ("job", models.CharField(max_length=30)),
                ("début", models.DateTimeField()),
                ("fin", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diplôme", models.CharField(max_length=60)),
                ("date_obtention", models.DateField()),
            ],
        ),
    ]
